version: '3.8'

services:
  backend1:
    build:
      context: ./backend1
    container_name: backend1
    expose:
      - "5001"

  backend2:
    build:
      context: ./backend2
    container_name: backend2
    expose:
      - "5002"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
